language: bash
services: docker

env:
  - VERSION=1.9 VARIANT=stretch
  - VERSION=1.9 VARIANT=alpine3.6
  - VERSION=1.8 VARIANT=jessie
  - VERSION=1.8 VARIANT=stretch
  - VERSION=1.8 VARIANT=alpine3.6
  - VERSION=1.8 VARIANT=alpine3.5

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="golang:$VERSION${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"
# the "onbuild" variant has to happen with the base variant because it's FROM it
  - if [ -z "$VARIANT" ] && [ -d onbuild ]; then travis_retry docker build -t "${image}-onbuild" onbuild; fi

after_script:
  - docker images

# vim:set et ts=2 sw=2:
